sudo: false
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy-5.4.1
    - pypy3.3-5.2-alpha1
install:
    - pip install mock coverage coveralls
    - pip install .
script:
    - coverage run --source=src/restview setup.py test -q
after_success:
    - coveralls
notifications:
    email: false
